### PR TITLE
Update libpng to version 1.6.24

### PR DESCRIPTION
**Pull request by ToninoTarsi**

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Wrong author/committer name/email.

**Comment by ToninoTarsi** [comment]
We discuss this on the development forum. 
What "Wrong author/committer name/email." means ??????

**Comment by MaxKellermann** [comment]
Author: tonySaipem <tonySaipem@tony-VirtualBox>  2016-08-18 10:38:13
Committer: tonySaipem <tonySaipem@tony-VirtualBox>  2016-08-18 10:38:13

Your name is not "tonySaipem", and your email address is not "tony-VirtualBox".

**Comment by MaxKellermann** [comment]
That new commit adds a space before the comma:

    -    'lib/libpng.a',
    +    'lib/libpng.a' ,

But why?

The old commit still hasn't got the correct authorship.

**Comment by ToninoTarsi** [comment]
Sorry max .. I was just trying to change the authorship in my eclipse git env.
I did not know how to change the authorship  of the old commit.
The new one is from tony.tarsi@gmail.com
Maybe it would be simpler for you to merge manualy.
Tony

**Comment by MaxKellermann** [comment]
If I have to fix up your commits, I can do it myself in the first place. That doesn't help me. Please learn how to use your tools.

**Pull request closed without merging**
