### PR TITLE
Thermal Express device driver, simplified version, started all again.

### PR DESCRIPTION
**Pull request by gmdimitriz**
Please, i started all again, made from zero, removed the MANAGE functions, i put just the minimum i need to work...

thanks

### CODE REVIEW

**Comment by gmdimitriz** [comment]
Waiting your position, thanks

**Comment by MaxKellermann** [comment]
Since you didn't get it at the first time, let me repeat myself:
> First you should fold those commits.  I don't want to merge known-bad commits and bunches of small fixup commits.  I can't review that.

**Comment by gmdimitriz** [comment]
ok, i did not do that before because if i fold it lost all your comments ... so i did it now...

**Comment by gmdimitriz** [comment]
so, i have to always get just one commit, right? even if it erase all history of comments?

**Comment by gmdimitriz** [comment]
i need to to anything else?

**Pull request closed without merging**
